name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install flake8

      - name: Lint
        run: |
          flake8 scripts app.py --max-line-length=120 || true

      - name: Sanity import checks
        run: |
          python - << 'PY'
          import importlib
          for mod in [
              'boto3', 'flask', 'flask_cors', 'serial', 'pynmea2']:
              importlib.import_module(mod)
          print('Imports OK')
          PY 